/**
 * B1 — Deterministic noise stripping for PR diffs.
 *
 * Classifies diff files as noise via priority-ordered heuristics,
 * then collapses their hunks into a one-line synthetic note. The
 * rewritten unified diff still parses through parseChangedRegions.
 *
 * All classification is local and deterministic: no network, no LLM.
 */

import type { GitRunner } from "./ingest.ts";

// ---------------------------------------------------------------------------
// Constants — override via opts for testability
// ---------------------------------------------------------------------------

/** Lock-file paths matched by basename (exact). */
export const LOCKFILE_NAMES: readonly string[] = [
  "pnpm-lock.yaml",
  "yarn.lock",
  "package-lock.json",
  "Cargo.lock",
  "go.sum",
  "go.work.sum",
  "poetry.lock",
  "Pipfile.lock",
  "Gemfile.lock",
  "composer.lock",
];

/** Path fragments that mark generated/vendor dirs or file patterns. */
export const NOISE_PATH_PATTERNS: readonly RegExp[] = [
  /\.min\.[^/]+$/,
  /\/dist\//,
  /^dist\//,
  /\/build\//,
  /^build\//,
  /\/__snapshots__\//,
  /\.snap$/,
  /\.pb\.[^/]+$/,
  /\.generated\.[^/]+$/,
  /\/vendor\//,
  /^vendor\//,
  /\/node_modules\//,
];

/** Header-line markers that indicate generated files. */
export const GENERATED_MARKERS: readonly string[] = [
  "@generated",
  "Code generated by",
  "DO NOT EDIT",
  "THIS FILE IS AUTO-GENERATED",
  "Auto-generated by",
  "Generated by",
];

/**
 * A single-file diff above this many changed lines with near-zero variety
 * is classified as size-noise.
 */
export const SIZE_NOISE_THRESHOLD_LINES = 500;
/** Ratio of non-diff content (blanks + identical lines) below which it's noisy. */
export const SIZE_NOISE_VARIETY_RATIO = 0.05;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type NoiseReason =
  | "gitattributes-linguist"
  | "generated-header"
  | "path-heuristic"
  | "size-heuristic";

export interface NoiseVerdict {
  isNoise: boolean;
  reason?: NoiseReason;
  detail?: string;
}

export interface NoiseOpts {
  lockfileNames?: readonly string[];
  noisePathPatterns?: readonly RegExp[];
  generatedMarkers?: readonly string[];
  sizeThresholdLines?: number;
  sizeVarietyRatio?: number;
  /** Injectable GitRunner for git check-attr; skip gitattributes check if absent. */
  git?: GitRunner;
  /** Working directory for git commands. */
  cwd?: string;
}

/** A noise file entry appended to ChangeSet.noiseFiles. */
export interface NoiseFile {
  path: string;
  reason: string;
  added: number;
  removed: number;
}

/**
 * Classify a single file path (+ optional hunk text for size heuristic).
 * Priority order: gitattributes -> generated-header -> path-heuristic -> size-heuristic.
 *
 * The gitattributes check requires a GitRunner + cwd and is async; all others are sync.
 * Call classifyNoiseSync for a synchronous subset (skips gitattributes).
 */
export async function classifyNoise(
  filePath: string,
  hunkText?: string,
  opts: NoiseOpts = {},
): Promise<NoiseVerdict> {
  // 1. gitattributes linguist check (async)
  if (opts.git && opts.cwd) {
    try {
      const out = await opts.git(
        ["check-attr", "linguist-generated", "linguist-vendored", "--", filePath],
        opts.cwd,
      );
      if (
        out.includes("linguist-generated: set") ||
        out.includes("linguist-generated: true") ||
        out.includes("linguist-vendored: set") ||
        out.includes("linguist-vendored: true")
      ) {
        return { isNoise: true, reason: "gitattributes-linguist", detail: out.trim() };
      }
    } catch {
      // git check-attr failure is non-fatal; fall through
    }
  }

  return classifyNoiseSync(filePath, hunkText, opts);
}

/** Synchronous classifier — skips the gitattributes check. */
export function classifyNoiseSync(
  filePath: string,
  hunkText?: string,
  opts: NoiseOpts = {},
): NoiseVerdict {
  const lockfiles = opts.lockfileNames ?? LOCKFILE_NAMES;
  const patterns = opts.noisePathPatterns ?? NOISE_PATH_PATTERNS;
  const markers = opts.generatedMarkers ?? GENERATED_MARKERS;
  const sizeThreshold = opts.sizeThresholdLines ?? SIZE_NOISE_THRESHOLD_LINES;
  const varietyRatio = opts.sizeVarietyRatio ?? SIZE_NOISE_VARIETY_RATIO;

  // 2. Generated-header markers in hunkText (first ~20 lines of the diff body)
  if (hunkText) {
    const head = hunkText.split("\n").slice(0, 20).join("\n");
    for (const marker of markers) {
      if (head.includes(marker)) {
        return { isNoise: true, reason: "generated-header", detail: marker };
      }
    }
  }

  // 3. Path heuristics — lockfiles by basename
  const basename = filePath.split("/").pop() ?? filePath;
  if (lockfiles.includes(basename)) {
    return { isNoise: true, reason: "path-heuristic", detail: "lockfile" };
  }
  for (const pattern of patterns) {
    if (pattern.test(filePath)) {
      return { isNoise: true, reason: "path-heuristic", detail: pattern.source };
    }
  }

  // 4. Size heuristic
  if (hunkText) {
    const lines = hunkText.split("\n");
    const addedOrRemoved = lines.filter((l) => l.startsWith("+") || l.startsWith("-")).length;
    if (
      addedOrRemoved > sizeThreshold &&
      lines.length > 0 &&
      addedOrRemoved / lines.length > (1 - varietyRatio)
    ) {
      return {
        isNoise: true,
        reason: "size-heuristic",
        detail: `${addedOrRemoved} changed lines`,
      };
    }
  }

  return { isNoise: false };
}

/** Count +/- lines in a hunk text block. */
function countDiffLines(hunkText: string): { added: number; removed: number } {
  let added = 0;
  let removed = 0;
  for (const line of hunkText.split("\n")) {
    if (line.startsWith("+") && !line.startsWith("+++")) added++;
    else if (line.startsWith("-") && !line.startsWith("---")) removed++;
  }
  return { added, removed };
}

/**
 * Rewrite a unified diff, collapsing noise files to a one-line synthetic hunk.
 *
 * The synthetic hunk is structured as a valid unified-diff hunk that parseChangedRegions
 * can parse: it produces a one-line RIGHT region so the file remains in the changed-
 * regions map (preserving existence signal) while the full diff body is discarded.
 *
 * Returns the rewritten diff string and the list of noise files.
 */
export async function collapseNoise(
  unifiedDiff: string,
  opts: NoiseOpts = {},
): Promise<{ diff: string; noiseFiles: NoiseFile[] }> {
  const blocks = splitDiffBlocks(unifiedDiff);
  const outputBlocks: string[] = [];
  const noiseFiles: NoiseFile[] = [];

  for (const block of blocks) {
    const filePath = extractFilePath(block);
    if (!filePath) {
      outputBlocks.push(block);
      continue;
    }

    const verdict = await classifyNoise(filePath, block, opts);
    if (!verdict.isNoise) {
      outputBlocks.push(block);
      continue;
    }

    const { added, removed } = countDiffLines(block);
    noiseFiles.push({ path: filePath, reason: verdict.reason ?? "unknown", added, removed });

    const note = `# ${filePath} changed (+${added}/-${removed}) -- present, not reviewed (${verdict.reason ?? "noise"})`;
    const syntheticBlock = [
      `diff --git a/${filePath} b/${filePath}`,
      `--- a/${filePath}`,
      `+++ b/${filePath}`,
      `@@ -0,0 +1,1 @@`,
      `+${note}`,
      "",
    ].join("\n");
    outputBlocks.push(syntheticBlock);
  }

  return { diff: outputBlocks.join(""), noiseFiles };
}

/** Split a unified diff string into per-file blocks (each starting with "diff --git"). */
function splitDiffBlocks(unifiedDiff: string): string[] {
  // Work on lines including their original newline by splitting on the line boundary
  // but keeping the newline with each line. We do this by splitting on \n and re-joining.
  const rawLines = unifiedDiff.split("\n");
  // The last element after split is "" if the string ended with \n — don't re-add a \n there.
  const blocks: string[] = [];
  let current = "";
  for (let i = 0; i < rawLines.length; i++) {
    const line = rawLines[i];
    const isLast = i === rawLines.length - 1;
    const lineWithNl = isLast ? line : line + "\n";
    if (line.startsWith("diff --git ") && current) {
      blocks.push(current);
      current = lineWithNl;
    } else {
      current += lineWithNl;
    }
  }
  if (current.trim()) blocks.push(current);
  return blocks;
}

/** Extract the b-side file path from a diff block header. */
function extractFilePath(block: string): string | null {
  const lines = block.split("\n");
  for (const line of lines) {
    if (line.startsWith("+++ b/")) {
      return line.slice(6).trim();
    }
    if (line.startsWith("+++ /dev/null")) {
      for (const l of lines) {
        if (l.startsWith("--- a/")) return l.slice(6).trim();
      }
    }
  }
  return null;
}
