import { describe, expect, it } from "vitest";

import { parseChangedRegions } from "../context/diff.ts";
import type { GitRunner } from "./ingest.ts";
import {
  classifyNoise,
  classifyNoiseSync,
  collapseNoise,
  GENERATED_MARKERS,
  LOCKFILE_NAMES,
  NOISE_PATH_PATTERNS,
} from "./noise.ts";

// ---------------------------------------------------------------------------
// classifyNoiseSync
// ---------------------------------------------------------------------------

describe("classifyNoiseSync", () => {
  it("returns isNoise=false for a clean source file", () => {
    const v = classifyNoiseSync("src/utils.ts");
    expect(v.isNoise).toBe(false);
  });

  it("detects generated-header marker in hunk text", () => {
    const hunk = `diff --git a/foo.ts b/foo.ts\n// DO NOT EDIT\n+some line\n`;
    const v = classifyNoiseSync("src/foo.ts", hunk);
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("generated-header");
    expect(v.detail).toBe("DO NOT EDIT");
  });

  it("detects @generated marker", () => {
    const hunk = `// @generated by protoc\n+line\n`;
    const v = classifyNoiseSync("proto/foo.ts", hunk);
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("generated-header");
  });

  it("detects lockfile by basename — yarn.lock", () => {
    const v = classifyNoiseSync("yarn.lock");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
    expect(v.detail).toBe("lockfile");
  });

  it("detects lockfile by basename — pnpm-lock.yaml in subdirectory", () => {
    const v = classifyNoiseSync("packages/web/pnpm-lock.yaml");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });

  it("detects .min.js path pattern", () => {
    const v = classifyNoiseSync("static/bundle.min.js");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });

  it("detects /dist/ path pattern", () => {
    const v = classifyNoiseSync("packages/core/dist/index.js");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });

  it("detects vendor/ path pattern", () => {
    const v = classifyNoiseSync("vendor/github.com/some/pkg/file.go");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });

  it("detects .snap files", () => {
    const v = classifyNoiseSync("src/__tests__/__snapshots__/MyComp.test.ts.snap");
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });

  it("detects size-noise when changed lines exceed threshold with low variety", () => {
    // Build a hunk with 600 pure-add lines
    const addLines = Array.from({ length: 600 }, (_, i) => `+line ${i}`).join("\n");
    const hunk = `diff --git a/big.ts b/big.ts\n--- a/big.ts\n+++ b/big.ts\n@@ -0,0 +1,600 @@\n${addLines}\n`;
    const v = classifyNoiseSync("big.ts", hunk, { sizeThresholdLines: 500, sizeVarietyRatio: 0.05 });
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("size-heuristic");
  });

  it("does NOT flag size-noise when below threshold", () => {
    const addLines = Array.from({ length: 100 }, (_, i) => `+line ${i}`).join("\n");
    const hunk = `@@ -0,0 +1,100 @@\n${addLines}\n`;
    const v = classifyNoiseSync("src/small.ts", hunk);
    expect(v.isNoise).toBe(false);
  });

  it("respects custom lockfileNames override", () => {
    const v = classifyNoiseSync("pnpm-lock.yaml", undefined, {
      lockfileNames: ["other.lock"],
    });
    // pnpm-lock.yaml is not in the custom list
    expect(v.isNoise).toBe(false);
  });

  it("exports expected constants", () => {
    expect(LOCKFILE_NAMES).toContain("yarn.lock");
    expect(NOISE_PATH_PATTERNS.length).toBeGreaterThan(0);
    expect(GENERATED_MARKERS).toContain("DO NOT EDIT");
  });
});

// ---------------------------------------------------------------------------
// classifyNoise (async, with GitRunner)
// ---------------------------------------------------------------------------

describe("classifyNoise", () => {
  it("returns gitattributes-linguist when git check-attr says linguist-generated: set", async () => {
    const fakeGit: GitRunner = async (args) => {
      if (args[0] === "check-attr") return "src/proto.ts: linguist-generated: set\n";
      throw new Error("unexpected");
    };
    const v = await classifyNoise("src/proto.ts", undefined, {
      git: fakeGit,
      cwd: "/repo",
    });
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("gitattributes-linguist");
  });

  it("falls through to sync path when git check-attr returns unset", async () => {
    const fakeGit: GitRunner = async () =>
      "src/utils.ts: linguist-generated: unset\n";
    const v = await classifyNoise("src/utils.ts", undefined, {
      git: fakeGit,
      cwd: "/repo",
    });
    expect(v.isNoise).toBe(false);
  });

  it("falls through to sync path when git check-attr throws", async () => {
    const throwGit: GitRunner = async () => {
      throw new Error("git not available");
    };
    // yarn.lock is still noise via path-heuristic
    const v = await classifyNoise("yarn.lock", undefined, {
      git: throwGit,
      cwd: "/repo",
    });
    expect(v.isNoise).toBe(true);
    expect(v.reason).toBe("path-heuristic");
  });
});

// ---------------------------------------------------------------------------
// collapseNoise
// ---------------------------------------------------------------------------

const CLEAN_FILE_DIFF = `diff --git a/src/limiter.ts b/src/limiter.ts
--- a/src/limiter.ts
+++ b/src/limiter.ts
@@ -1,1 +1,3 @@
 export class Limiter {}
+  // added line 1
+  // added line 2
`;

const LOCKFILE_DIFF = `diff --git a/yarn.lock b/yarn.lock
--- a/yarn.lock
+++ b/yarn.lock
@@ -1,2 +1,3 @@
-old dep
+new dep
+another dep
`;

const MIXED_DIFF = CLEAN_FILE_DIFF + LOCKFILE_DIFF;

describe("collapseNoise", () => {
  it("returns noise-free diff unchanged and empty noiseFiles array", async () => {
    const result = await collapseNoise(CLEAN_FILE_DIFF);
    expect(result.noiseFiles).toEqual([]);
    expect(result.diff).toContain("src/limiter.ts");
    // Hunk lines preserved
    expect(result.diff).toContain("added line 1");
  });

  it("collapses a lockfile to a synthetic hunk and records noiseFiles entry", async () => {
    const result = await collapseNoise(LOCKFILE_DIFF);
    expect(result.noiseFiles).toHaveLength(1);
    expect(result.noiseFiles[0].path).toBe("yarn.lock");
    expect(result.noiseFiles[0].reason).toBe("path-heuristic");
    expect(result.noiseFiles[0].added).toBe(2);
    expect(result.noiseFiles[0].removed).toBe(1);
    // Original content gone
    expect(result.diff).not.toContain("old dep");
    expect(result.diff).not.toContain("new dep");
    // Synthetic note present
    expect(result.diff).toContain("yarn.lock");
    expect(result.diff).toContain("present, not reviewed");
  });

  it("handles mixed diff: noise collapsed, non-noise preserved", async () => {
    const result = await collapseNoise(MIXED_DIFF);
    expect(result.noiseFiles).toHaveLength(1);
    expect(result.noiseFiles[0].path).toBe("yarn.lock");
    // Clean file hunk still has its content
    expect(result.diff).toContain("added line 1");
    // Lockfile original content gone
    expect(result.diff).not.toContain("old dep");
  });

  it("synthetic hunk parses through parseChangedRegions and yields 1 RIGHT region at line 1", async () => {
    const result = await collapseNoise(LOCKFILE_DIFF);
    const regions = parseChangedRegions(result.diff);
    const lockfileRegions = regions.filter((r: { file: string }) => r.file === "yarn.lock");
    expect(lockfileRegions).toHaveLength(1);
    expect(lockfileRegions[0].side).toBe("RIGHT");
    expect(lockfileRegions[0].startLine).toBe(1);
    expect(lockfileRegions[0].endLine).toBe(1);
  });

  it("non-noise file regions are correct after collapse", async () => {
    const result = await collapseNoise(MIXED_DIFF);
    const regions = parseChangedRegions(result.diff);
    const limiterRegions = regions.filter((r: { file: string }) => r.file === "src/limiter.ts");
    expect(limiterRegions.length).toBeGreaterThan(0);
  });
});
